spring.application.name=Infinitum-Art
spring.datasource.url=jdbc:postgresql://postgres-db:5432/appdb
spring.datasource.username=appuser
spring.datasource.password=apppass
spring.datasource.driver-class-name=org.postgresql.Driver
# Creates/updates tables
spring.jpa.hibernate.ddl-auto=update

# Show SQL for debugging
spring.jpa.show-sql=true
#my-secret-key-1234567890-abcd-*/
jwt.secret=bXktc2VjcmV0LWtleS0xMjM0NTY3ODkwLWFiY2QtKi8=
jwt.expiration=86400000
jwt.verifyExpiration= 3600000

#Mail sender configurations
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=iliasse20001@gmail.com
spring.mail.password=luaxauysgfcsojvw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.supportEmail=iliasse20001@gmail.com

#debuging
logging.level.com.Project_INTELLCAP.Infinitum_Art=DEBUG
logging.level.org.springframework.security=DEBUG

#Front informations
app.frontend.base-url=http://localhost:8080

# File upload configuration
app.upload.dir=uploads/profiles
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
