# k8s/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tp-devops-ingress
  # Il n'y a plus besoin d'annotations pour ce cas
spec:
  # ✅ CORRECT : C'est un champ de la spécification ('spec')
  ingressClassName: "webapprouting.kubernetes.azure.com"
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tp-devops-service
            port:
              number: 80